[phases.install]
  cmds = [
    # Ensure we are in the bot workspace
    "npm install"
  ]

[phases.build]
  cmds = [
    "npm run build",
    "npm run prisma:generate"
  ]

[start]
  cmd = "npm start"
